platform :ios, '7.0' 
target 'LittleJumpingFrog' do
	pod 'AFNetworking','~>3.0'
	pod 'YYKit'
	pod 'Masonry'
	pod 'MTLog'
	pod 'MJRefresh'
	pod 'NAKPlaybackIndicatorView'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'pop', '~> 1.0'
	pod 'DOUAudioStreamer', '0.2.11'
	pod 'GVUserDefaults'
    pod 'Reachability'
    pod 'GYDataCenter'
    pod 'SSZipArchive'
    pod 'FMDB'
    pod 'PYSearch'
end
